# Generated by Django 4.0.3 on 2022-08-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
